### PR TITLE
Improve ThreadPoolExecutor

### PR DESCRIPTION
**Pull request by SergeyLabutin**

### CODE REVIEW

**Comment by intrigus** [comment]
How is this more efficient?
Why is an ArrayList more efficient than an ordinary Array?

**Comment by SergeyLabutin** [comment]
Array with MAXINT is unsafe, in java array limit is MAXINT-8.

**Comment by soywiz** [comment]
BTW if you are going to use threads, we should implement synchronized methods. It should be as easy as change the method body with synchronized keyword to:

```
enterMonitor(this);
try {
    // actual body...
} finally {
    exitMonitor(this);
}
```

Even when pretty easy, this is not implementred yet. So if you have concurrency problems. It could be related to this.

Also we should override in HaxeGenerator:
```
open fun genStmMonitorEnter(stm: AstStm.MONITOR_ENTER) = indent { line("// MONITOR_ENTER") }
open fun genStmMonitorExit(stm: AstStm.MONITOR_EXIT) = indent { line("// MONITOR_EXIT") }
```

And call to `N.enterMonitor` and `N.exitMonitor` if it is not done already. And we will probably have to `@AddHaxeMembers` to `java.lang.Object` with a lock to use http://api.haxe.org/cpp/vm/Lock.html

**Comment by intrigus** [comment]
> Array with MAXINT is unsafe, in java array limit is MAXINT-8.

Would love to see a source for this claim.
Anyway, this limit may be true for a particular vm version, but jtransc doesn't impose this limit as far as I know.
Also no one is going to allocate MAXINT tasks...

**Comment by SergeyLabutin** [comment]
https://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size

**Comment by SergeyLabutin** [comment]
> Also no one is going to allocate MAXINT tasks...

Before this Pull Request this create array with MAXINT
```
public class ScheduledThreadPoolExecutor extends ThreadPoolExecutor implements ScheduledExecutorService {
	public ScheduledThreadPoolExecutor(int corePoolSize) {
		super(corePoolSize, Integer.MAX_VALUE, 0, TimeUnit.NANOSECONDS, new DelayedWorkQueue());
	}
```

**Pull request merged**
