### PR TITLE
Fix thread mapping

### PR DESCRIPTION
**Pull request by SergeyLabutin**

### CODE REVIEW

**Comment by SergeyLabutin** [comment]
@soywiz please see it, on my windows computer test competed without errors, and AppVeyor too, but something with travis =(

**Comment by soywiz** [comment]
I'm checking it

**Comment by soywiz** [comment]
I get this error on mac:

![captura de pantalla 2017-08-02 a las 18 33 55](https://user-images.githubusercontent.com/570848/28884207-3a7f7b86-77b1-11e7-8ef1-90f8a089c591.png)

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:54553,suspend=y,server=n -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Users/soywiz/Library/Caches/IdeaIC2017.1/groovyHotSwap/gragent.jar -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/lib/tools.jar:/Users/soywiz/Projects/kor/jtransc/jtransc-main/build/classes/test:/Users/soywiz/Projects/kor/jtransc/jtransc-main/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-main/build/resources/test:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-core/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-core/build/resources/main:/Users/soywiz/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar:/Users/soywiz/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar:/Users/soywiz/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/soywiz/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/soywiz/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar:/Users/soywiz/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar:/Users/soywiz/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.jar:/Users/soywiz/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.3.9/f43afa184555fbc6e36b3334b17246c39b30f6e/maven-artifact-3.3.9.jar:/Users/soywiz/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar:/Users/soywiz/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar:/Users/soywiz/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar:/Users/soywiz/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.jar:/Users/soywiz/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-io/2.0.3/plexus-io-2.0.3.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar:/Users/soywiz/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/soywiz/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.5.2/plexus-classworlds-2.5.2.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.0/199b7acaa05b570bbccf31be998f013963e5e752/guice-4.0-no_aop.jar:/Users/soywiz/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.2/org.eclipse.sisu.plexus-0.3.2.jar:/Users/soywiz/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-aether-provider/3.3.9/maven-aether-provider-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-model-builder/3.3.9/maven-model-builder-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-plugin-api/3.3.9/maven-plugin-api-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-settings-builder/3.3.9/maven-settings-builder-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-compat/3.0/maven-compat-3.0.jar:/Users/soywiz/.m2/repository/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.jar:/Users/soywiz/.m2/repository/org/eclipse/aether/aether-api/1.1.0/aether-api-1.1.0.jar:/Users/soywiz/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0/maven-artifact-resolver-1.0.jar:/Users/soywiz/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1.1/plexus-archiver-2.1.1.jar:/Users/soywiz/.m2/repository/org/apache/maven/maven-core/3.3.9/maven-core-3.3.9.jar:/Users/soywiz/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.4/maven-plugin-annotations-3.4.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/Users/soywiz/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-as3/build/classes/test:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-as3/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-as3/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-php/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-php/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-cs/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-cs/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-d/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-d/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-cpp/build/classes/test:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-cpp/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-cpp/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-js/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-js/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-haxe/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-haxe/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-asm/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-annotations/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-utils/build/classes/test:/Users/soywiz/Projects/kor/jtransc/jtransc-utils/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-utils/build/resources/test:/Users/soywiz/Projects/kor/jtransc/jtransc-core/build/classes/test:/Users/soywiz/Projects/kor/jtransc/jtransc-core/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-core/build/resources/test:/Users/soywiz/Projects/kor/jtransc/jtransc-core/build/resources/main:/Users/soywiz/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/soywiz/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-core-kotlin/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-rt/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-rt/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-dart/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-gen-dart/build/resources/main:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-extended-charsets/build/classes/test:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-extended-charsets/build/classes/main:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-extended-charsets/build/resources/test:/Users/soywiz/Projects/kor/jtransc/jtransc-rt-extended-charsets/build/resources/main:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.1.2-3/552a40eb47669b78f0f194d526cb21b3aa1f8319/kotlin-stdlib-1.1.2-3.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-runtime/1.1.2-3/cb5571ee33ecca819ee516c9a07cee9756fdb42e/kotlin-runtime-1.1.2-3.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.1.2-3/cd6793e24cbcffa73ae823fa922bc882cef5d10b/kotlin-reflect-1.1.2-3.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.rauschig/jarchivelib/0.7.1/47a77274cc38cfe6c04bc2afa3ece808742dc42b/jarchivelib-0.7.1.jar:/Users/soywiz/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.9/cc18955ff1e36d5abd39a14bfe82b19154330a34/commons-compress-1.9.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 HaxeTest,testBigCpp
objc[6571]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java (0x1097e24c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10a88d4e0). One of the two will be used. Which one is undefined.
Connected to the target VM, address: '127.0.0.1:54553', transport: 'socket'
big.BigTest
Execute command /usr/local/bin/haxe -cp /var/folders/ml/lqvyyrkx533gczw6tyx9sc1h0000gn/T/jtransc/0_0/jtransc-haxe/src -main big/BigTest_EntryPoint_.hx -debug -cpp /var/folders/ml/lqvyyrkx533gczw6tyx9sc1h0000gn/T/jtransc/0_0/jtransc-haxe/program.exe -D HXCPP_M64 -D no-analyzer
haxelib run hxcpp Build.xml haxe -Ddebug -DHXCPP_M64="1" -Dhaxe3="1" -Dhaxe_ver="3.4" -Dhxcpp_api_level="331" -Dno-analyzer="1" -Dno_analyzer="1" -Dsource-header="Generated by Haxe 3.4.0" -I"/var/folders/ml/lqvyyrkx533gczw6tyx9sc1h0000gn/T/jtransc/0_0/jtransc-haxe/src/" -I"/usr/lib/haxe/extraLibs/" -I"/usr/local/lib/haxe/extraLibs/" -I"" -I"/usr/lib/haxe/std/cpp/_std/" -I"/usr/share/haxe/std/cpp/_std/" -I"/usr/local/lib/haxe/std/cpp/_std/" -I"/usr/lib/haxe/std/" -I"/usr/share/haxe/std/" -I"/usr/local/lib/haxe/std/"
In file included from /usr/local/lib/haxe/lib/hxcpp/3,4,2/include/hxcpp.h:317:
/usr/local/lib/haxe/lib/hxcpp/3,4,2/include/null.h:132:61: warning: binding dereferenced null pointer to reference has undefined behavior [-Wnull-dereference]
        { hx::NullReference("Function Call", false); return *(Dynamic *)0; }
                                                            ^~~~~~~~~~~~~
Creating /private/var/folders/ml/lqvyyrkx533gczw6tyx9sc1h0000gn/T/jtransc/0_0/jtransc-haxe/program.exe/obj/darwin64-debug/__pch/haxe/hxcpp.h.gch...

Compiling group: haxe
g++ -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -g -I/usr/local/lib/haxe/lib/hxcpp/3,4,2/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=331(haxe) ... tags=[haxe,static]
 - src/testservice/TestServiceImpl1_.cpp 
1 warning generated.
Error: In file included from ./src/testservice/ITestService_Proxy_.cpp:2:
In file included from /usr/local/lib/haxe/lib/hxcpp/3,4,2/include/hxcpp.h:317:
/usr/local/lib/haxe/lib/hxcpp/3,4,2/include/null.h:132:61: warning: binding dereferenced null pointer to reference has undefined behavior [-Wnull-dereference]
        { hx::NullReference("Function Call", false); return *(Dynamic *)0; }
                                                            ^~~~~~~~~~~~~
./src/testservice/ITestService_Proxy_.cpp:57:1: error: C++ requires a type specifier for all declarations
HX_LOCAL_STACK_FRAME(_hx_pos_0f9aeb3a76402ea1_8_testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V,"testservice.ITestService_Proxy_","testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V",0xa8843637,"testservice.ITestService_Proxy_.testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V","testservice/ITestService_Proxy_.hx",8,0x091baf34)
^
./src/testservice/ITestService_Proxy_.cpp:57:22: error: use of undeclared identifier '_hx_pos_0f9aeb3a76402ea1_8_testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V'
HX_LOCAL_STACK_FRAME(_hx_pos_0f9aeb3a76402ea1_8_testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V,"testservice.ITestService_Proxy_","testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V",0xa8843637,"testservice.ITestService_Proxy_.testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V","testservice/ITestService_Proxy_.hx",8,0x091baf34)
                     ^
./src/testservice/ITestService_Proxy_.cpp:57:411: error: expected ';' after top level declarator
HX_LOCAL_STACK_FRAME(_hx_pos_0f9aeb3a76402ea1_8_testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V,"testservice.ITestService_Proxy_","testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V",0xa8843637,"testservice.ITestService_Proxy_.testservice_ITestService_Proxy_init__Ljava_lang_reflect_InvocationHandler__V","testservice/ITestService_Proxy_.hx",8,0x091baf34)
                                                                                                                                                                                                                                                                                                                                                                                                                          ^
                                                                                                                                                                                                                                                                                                                                                                                                                          ;
1 warning and 3 errors generated.
Error: In file included from ./src/testservice/TestServiceImpl1_.cpp:2:
In file included from /usr/local/lib/haxe/lib/hxcpp/3,4,2/include/hxcpp.h:317:
/usr/local/lib/haxe/lib/hxcpp/3,4,2/include/null.h:132:61: warning: binding dereferenced null pointer to reference has undefined behavior [-Wnull-dereference]
        { hx::NullReference("Function Call", false); return *(Dynamic *)0; }
                                                            ^~~~~~~~~~~~~
./src/testservice/TestServiceImpl1_.cpp:36:1: error: C++ requires a type specifier for all declarations
HX_LOCAL_STACK_FRAME(_hx_pos_77a04890bbe3980b_8_testservice_TestServiceImpl1_init___V,"testservice.TestServiceImpl1_","testservice_TestServiceImpl1_init___V",0x3b19ced4,"testservice.TestServiceImpl1_.testservice_TestServiceImpl1_init___V","testservice/TestServiceImpl1_.hx",8,0x0cc4cdd9)
^
./src/testservice/TestServiceImpl1_.cpp:36:22: error: use of undeclared identifier '_hx_pos_77a04890bbe3980b_8_testservice_TestServiceImpl1_init___V'
HX_LOCAL_STACK_FRAME(_hx_pos_77a04890bbe3980b_8_testservice_TestServiceImpl1_init___V,"testservice.TestServiceImpl1_","testservice_TestServiceImpl1_init___V",0x3b19ced4,"testservice.TestServiceImpl1_.testservice_TestServiceImpl1_init___V","testservice/TestServiceImpl1_.hx",8,0x0cc4cdd9)
                     ^
./src/testservice/TestServiceImpl1_.cpp:36:288: error: expected ';' after top level declarator
HX_LOCAL_STACK_FRAME(_hx_pos_77a04890bbe3980b_8_testservice_TestServiceImpl1_init___V,"testservice.TestServiceImpl1_","testservice_TestServiceImpl1_init___V",0x3b19ced4,"testservice.TestServiceImpl1_.testservice_TestServiceImpl1_init___V","testservice/TestServiceImpl1_.hx",8,0x0cc4cdd9)
                                                                                                                                                                                                                                                                                               ^
                                                                                                                                                                                                                                                                                               ;
1 warning and 3 errors generated.
 - src/testservice/ITestService_Proxy_.cpp 
Error: Build failed

Disconnected from the target VM, address: '127.0.0.1:54553', transport: 'socket'

org.junit.ComparisonFailure:  <Click to see difference>


	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at _Base.testClassNoLog(_Base.kt:87)
	at _Base.testClass(_Base.kt:65)
	at HaxeTest.testBigCpp(HaxeTest.kt:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

**Comment by soywiz** [comment]
I will set a ubuntu virtual machine later today to try to reproduce the problem. Also i should fix C# hang because i cannot run all tests on later versions of mono

**Comment by SergeyLabutin** [comment]
yep, i too have problem with C# on my mac #167 also with cpp #166 will be good if i can run test on mac with windows before push my code.

**Pull request merged**
