### PR TITLE
split getAllClasses for fix OOM in 32bit

### PR DESCRIPTION
**Pull request by SergeyLabutin**
@soywiz Maybe it crazy, but works for Haxecpp =) Please, review why not working testNanoHelloWorldShouldReferenceGetMethods

### CODE REVIEW

**Comment by SergeyLabutin** [comment]
Size for test program.js is 221.78KB, but test wait < 220KB, is it critical?

**Comment by soywiz** [comment]
@SergeyLabutin No it is not critical. It is just an assert to notice that we are growing the minimial program size. So it doesn't grow without noticing. We can grow the expected size if we are doing it conscientiously, or reduce if we are applying measures to reduce it.

**Comment by soywiz** [comment]
I think the method is misleading:

```testNanoHelloWorldShouldReferenceGetMethods``` // the name is wrong because it should be "shouldn't" instead of "should". Also it checks size too.

to something like -->

```testNanoHelloWorldShouldNotReferenceGetMethodsAndBeSmallEnough```

I know it is not related to your issue, but since you are modifying that file. Can you fix the name?

**Comment by SergeyLabutin** [comment]
Ok i make it

**Comment by SergeyLabutin** [comment]
oh, again verified on AppVeyor only, is it my fail?

**Comment by soywiz** [comment]
Not sure. That's strange. It fails on Haxe-C++ on linux. The problem is that the text diff doesn't give a clue about why is it failing. But seems to fail consistently and master is working. Though your changes seem unrelated.
Ill investigate further this afternoon. The output seems to come from testArrayCopy:

(I have run BigTest.main in java and searched for the common part)

```
testArrayCopy:
[false, false, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true]
[0, 0, 0, 9, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 9, 16, 25, 36, 9, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 9, 16, 25, 36, 9, 16, 9, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 49, 64, 81, 100, 121, -112, -87, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 49, 64, 81, 100, 49, 64, 81, 100, 121, -112, -87, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 49, 64, 81, 100, 49, 64, 49, 64, 81, 100, 121, -112, -87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 81, 100, 121, -112, -87, -60, -31, 64, 81, 100, 121, -112, -87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 81, 100, 121, -112, 81, 100, 121, -112, -87, -60, -31, -112, -87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 81, 100, 121, -112, 81, 100, 81, 100, 121, -112, -87, -60, -31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, -112, -87, -60, -31, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 9, 16, 25, 36, 9, 16, 25, 36, 49, 64, 81, -60, -31, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 9, 16, 25, 36, 9, 16, 9, 16, 25, 36, 9, 16, 25, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 9, 16, 9, 16, 25, 36, 9, 16, 25, 36, 9, 16, 25, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 9, 16, 9, 16, 25, 36, 9, 16, 25, 36, 9, 16, 25, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 9, 16, 9, 16, 25, 36, 25, 36, 9, 16, 25, 36, 9, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 25, 36, 9, 16, 25, 36, 9, 36, 9, 16, 25, 36, 9, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 25, 36, 9, 16, 9, 36, 9, 16, 25, 36, 9, 36, 9, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 1, 4, 25, 36, 9, 16, 9, 36, 9, 16, 25, 36, 9, 36, 9, 0, 33, 68, 105, -112, -71, -28, 17, 64, 113, -92, -39, 16, 73, -124, -63]
[0, 0, 0, 9, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 9, 16, 25, 36, 9, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 9, 16, 25, 36, 9, 16, 9, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 49, 64, 81, 100, 121, 144, 169, 16, 25, 36, 49, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 49, 64, 81, 100, 49, 64, 81, 100, 121, 144, 169, 64, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 49, 64, 81, 100, 49, 64, 49, 64, 81, 100, 121, 144, 169, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 81, 100, 121, 144, 169, 196, 225, 64, 81, 100, 121, 144, 169, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 81, 100, 121, 144, 81, 100, 121, 144, 169, 196, 225, 144, 169, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 81, 100, 121, 144, 81, 100, 81, 100, 121, 144, 169, 196, 225, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Pull request merged**
