### PR TITLE
Test for issue 146

### PR DESCRIPTION
**Pull request by SergeyLabutin**
#146

### CODE REVIEW

**Comment by soywiz** [comment]
Going to merge.
But thinking about this, I think that you should add these tests with `@Ignore`. Because if it fails, reports several places that fails. And if there are other pull requests. it makes everything fail even when unrelated issues.
I think the best way is to keep the issue open. Mark test as ignored and merge it. Then fix it and close the issue. Or at least merge it to a branch so unrelated issues are not affected.

What I'm going to do is to merge this and to put it in a `@Ignore`. Then when I fix I will close the issue #146

**Comment by SergeyLabutin** [comment]
Ok, i will in future make it (add `@Igrore`), before i add test for travis detect too, not my computer only =))
This common problem and add in BigTest, future i can add to HaxeTest only, maybe this better way?

**Comment by soywiz** [comment]
Here is what I did:

https://github.com/jtransc/jtransc/commit/3128e782e382dfdd83b8e6e5bb92de669710f80b

I usually consider two kind of tests:

* Tests that are small related to treeshaking/or static initialization that also reproduces on all targets because that is common to all. I put them alone. Also Use `JsTest` because pure JS target is fastest to generate sound and to run and doesn't require compiling at all.
* Tests that check functionality/behaviour of the VM/runtime. Sometimes even call native methods that end being different per target. I include those in BigTest. BigTest is a way to test as much as possible having to compile just once and run it per target. So we cover the whole/most funcionality here. It should run at least once per target so we can rest asured.

I could add one test per functionality, but that way we could end with travis taking 30 minutes or more to complete all tests. So the BigTest approach is a pragmatic solution to that problem.

Also you can add tests with `@Ignore` so you can run them manually in your target. But that are ignored in travis because already covered in BigTest.

This issue fails in all targets because it is related to treeshaking. You can check if it fails in JS too very easily. Just copying your test to JsTest class. If it fails, better to add to JsTest because of total compile/run time.

**Comment by SergeyLabutin** [comment]
Tnx, i will be made it in future.

**Pull request merged**
