### PR TITLE
fix scheduled submit

### PR DESCRIPTION
**Pull request by SergeyLabutin**
Also need support synchronized ASAP

### CODE REVIEW

**Comment by SergeyLabutin** [comment]
@soywiz Ops, delete log and test no passed, wtf? i do not understand what wrong =))

**Comment by soywiz** [comment]
'haxelib' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1

Maybe failed tenporarily? We can reeun it

**Comment by soywiz** [comment]
Add another dummy commit maybe it works now if it was a tenporal connection issue appveyor had

**Comment by SergeyLabutin** [comment]
Same result =(

**Comment by soywiz** [comment]
Try to edit appveyor file in root
cinst -y haxe --version=3.4.2 || ver>nul
maybe remove ver nul part to see if it provides more info about the error

**Pull request merged**
