### PR TITLE
Improve README and fix wrong comment

### PR DESCRIPTION
**Pull request by SergeyLabutin**
Improve README and fix wrong comment.

### CODE REVIEW

**Comment by soywiz** [comment]
Cool. Thanks!

**Comment by soywiz** [comment]
I thought I merged it with my mobile phone. But it seems it cannot merge automatically. I will have to merge it manually unless you update it to master

**Comment by SergeyLabutin** [comment]
Sorry, i first time use github. I try see more but maybe i wrong with merge request.

**Comment by SergeyLabutin** [comment]
I see graph, see as good. I don't know why problem with merge automatically. I wait. This changes is minor.

**Comment by soywiz** [comment]
Woops. That was strange. I just noticed that was not merged yesterday when pressed the button. And then tried with my phone a moment ago and did not work. Tried again in the computer and now it merges flawlessly. So, this is already done. Thanks for the PR!

**Pull request merged**
