### PR TITLE
Fix minitemplate if else

### PR DESCRIPTION
**Pull request by soywiz**

### CODE REVIEW

**Comment by soywiz** [comment]
This should fix https://github.com/jtransc/jtransc/issues/190

**Comment by soywiz** [comment]
That's strange if you have all versions right and installed this one. I was able to reproduce the problem in tests and fixed. But maybe I missed something.

When K get hime this night, i will try to reproduce the problem and update this PR if an additional fix is required.

If I cannot solve it, I will still release 0.6.5 without that additional fix, so we can have a release this week despite of that. At least this fix a spurious bug with if/else even if not fixes that specific case for other reason.

**Comment by SergeyLabutin** [comment]
I finish reinstall my mac  today. And try test again. You can release anyway, and will be work for 0.6.6

**Comment by soywiz** [comment]
Went to jtransc folder:
```
git checkout fix-minitemplate-if-else
type gradle.properties # <<- jtransc 0.6.4
./gradlew install
```

Went to gdx-backend-jtransc folder:
```
git checkout bugs/minitemple-if-else
type gradle.properties # <<- jtransc 0.6.4
./gradlew install
```

Went to `jtransc-examples/spine-demo` folder:
```
type gradale.properties # << jtransc 0.6.4
gradlew debugHaxecpp
type build\jtransc-haxe\src\com\jtransc\media\limelibgdx\LimeApplication_.hx
```

snag-0029
snag-0028

**Pull request merged**
