### PR TITLE
fix writeUTF

### PR DESCRIPTION
**Pull request by SergeyLabutin**

### CODE REVIEW

**Comment by SergeyLabutin** [comment]
@intrigus In Java doc next line
`First, two bytes are written to the output stream as if by the writeShort method giving the number of bytes to follow.`
If i mistake, get improve code.

**Comment by intrigus** [comment]
I'll have a close look at this tomorrow if this issue is not too critical for you :)
Maybe I'm overthinking it^^

**Comment by soywiz** [comment]
In fact modified UTF-8 is different in some edge cases:
https://docs.oracle.com/javase/7/docs/api/java/io/DataInput.html#modified-utf-8

If you are using to store a savegame it will break when fixed if you use edge cases. And if you are using it to serialize things between server and client and server runs on jvm, you will potentially have a problem. But as said, it seems to be different in edge cases like using \0 character.
I can implement modified UTF-8 as a charset in other PR.
Right now writeObject is totally broken anyway, and this implementation is better, though not perfect.

**Comment by SergeyLabutin** [comment]
> Right now writeObject is totally broken anyway, and this implementation is better, though not perfect.
I think i can not write better, this not my level. But i fixed it because really working with save in my game. And save will send to server and will download from native android too (without jtransc) =(

@intrigus i will wait your decision. This not critical right now, but need for make impl read/write preferences https://github.com/jtransc/gdx-backend-jtransc/tree/improvements/files

**Comment by intrigus** [comment]
@soywiz 
We need a modified UTF8 charset for this to work.
I just tested it and it fails currently.

Test:
````java
package javatest;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.Arrays;

public class DataOutputStreamTest {

	public static void main(String[] args) throws IOException {
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		DataOutputStream d = new DataOutputStream(out);
		d.writeUTF("hello\u0000");
		System.out.println(Arrays.toString(out.toByteArray()));
	}
}

````

**Comment by soywiz** [comment]
Here is an independent implementation as reference. In fact we have that class too, but it just redirects to plain UTF8.
https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/nio/charset/ModifiedUtf8.java

https://github.com/jtransc/jtransc/blob/e880096b22490e22487817bf3380528bdd5c5b92/jtransc-rt/src/java/nio/charset/ModifiedUtf8.java

So it should be as easy as implement right the ModifiedUtf8 class (using reference implementation) and call it instead of using UTF-8.

**Comment by soywiz** [comment]
I pushed to master unintentionally. But, I have updated ModifiedUtf8 https://github.com/jtransc/jtransc/commit/5f4ed95f04014c3ea14742aecd5bb13dd7419b6e
If you upddate master in this PR, you will be able to use ModifiedUtf8 in the new location that should work properly.
Also original names from this class are misleading. `encode` uses length, whilke `decode` doesn't uses length. I will fix names in other PR.
So you will have to call encode directly instead of writing length + encoded.

**Comment by soywiz** [comment]
```
public final void writeUTF(String str) throws IOException {
	write(str.getBytes(StandardCharsets.UTF_8));
}
```

->

```
public final void writeUTF(String str) throws IOException {
	byte[] data = str.getBytes(StandardCharsets.UTF_8);
	writeShort(data.length);
	write(data);
}
```

->

https://github.com/jtransc/jtransc/commit/5f4ed95f04014c3ea14742aecd5bb13dd7419b6e

```
public final void writeUTF(String str) throws IOException {
	write(ModifiedUtf8.encode(str));
}
```
```

**Comment by soywiz** [comment]
DataInputStream should use ModifiedUtf8 too

**Comment by soywiz** [comment]
Also i will fix appveyor today so merges can be done

**Pull request merged**
