### PR TITLE
CPP Target and small JS Target improvements

### PR DESCRIPTION
**Pull request by dsp-omen**

### CODE REVIEW

**Comment by dsp-omen** [comment]
It includes the "tree shaking" stuff. Just add treeshaking=true to gradle. Added yesterday, so not tested too much.

I have fixed several issues from the JS target too.

I have added a new set of tasks (gensrc*) to gradle plugin in order to generate C++ sources without compiling, so you can use a custom compiler in another gradle task (like g++ instead of clang or another C compiler for your target). It generates C++0x code. You can change it if you require a lower version of C++.

Probably it will have some issues.

Going to sleep. Feel free to do as many changes as you need. If you have any questions or problems I will reply them tomorrow.

**Comment by soywiz** [comment]
OMFG! That was for real!
And there are that many changes that I cannot review using github xD. Great job!
It seems that travis don't like the PR. But anyway I'm going to merge it and check it from my computer and will try to fix it from here.
Thank you so much!

**Comment by soywiz** [comment]
#24 #51

**Comment by soywiz** [comment]
I compiled this without issues. After adding clang to the path I was able to run tests.

It seems that Js tests are broken (at least in windows with a small issue regarding to paths). Also when commiting you drop the executable flag from some scripts that prevented travis to work.

Also c++ target doesn't pass all tests. As far as I noticed (running JTranscPerTargetBigTest.testPlainCpp):
* Some issues related to paths
* Arguments seems to be out of order in some cases
* It seems that annotations are not implemented
* The same goes for dynamic proxies
* java8 method references are not implemented (that last test doesn't run at all)

I don't see any code related to `@JtranscWeak`. How do you do to free cyclic references? As far as I have seen you are using `std::shared_ptr` for the ARC. So I suspect you are/should mark stuff and use std::weap_ptr in those cases.

But at any rate, this is amazing! I'm going to try to use it instead of haxe target. In fact I was generated a demo for psvita homebrew using haxe,c++, but had lots of issues. So with this probably will be easier. Additionally it seems that it generates a single file that comes pretty handy to use other compilers.
Thank you very much! :) 👍

**Comment by soywiz** [comment]
And just checked the treeshaking stuff. I had a js demo that sized 9mb, and now it is just 330kb! :D
I had to reimplement it before...

**Comment by soywiz** [comment]
I have released 0.4.0 with this. I have fixed some stuff. Though still there are some rough edges. I will try to fix them in 0.4.1 this weekend. Please, review the changes I have done.

**Comment by soywiz** [comment]
FYI. I have migrated my psvita demo from Haxe to your C++ target, and works like a charm :)

https://github.com/soywiz/psvita-java

**Comment by dsp-omen** [comment]
Path issues: It is definitely possible. I had to change some code to be able to hook I/O with some APIs of the microcontroller.

Argument order: In C++ the order of evaluation of expressions is undefined: http://en.cppreference.com/w/cpp/language/eval_order
So in order to get it working probably will have to create temporal local variables. It is possible that marking methods with __cdecl could fix the issues: http://stackoverflow.com/questions/621542/compilers-and-argument-order-of-evaluation-in-c My code don't rely on any specific order, so I didn't noticed.

Annotations, Dynamic Proxies, java8 methods: I didn't need them, so I did not implement them for now.

@JTranscWeak, the code is prepared for it, but my code is pretty simple and doesn't allocate too much, so I did not implement it yet.

I'm glad treeshaking works fine to you. I needed that, to keep the executable small.

Also I have reviewed your changes. Seems pretty logical to me, so I don't have anything to add. I had some random crashes. Probably due to the array descriptor fixed issue. So +1 for it. It is great that you released 0.4.0 that fast, though it will require some more polish.

Regarding to the psvita-java. I do not own a psvita, so I cannot test it, but it is also great that you can use it too, and that migrated it that fast. As I have seen you even discovered the JTRANSC_LIBS gradle extension property I added.

**Comment by soywiz** [comment]
I have tried __cdecl and worked on linux but failed on windows. So probably the best way is to create an AST transformer that go back from full expressions to a three-operand form just for the C++ target.

BTW: Can you write me to soywiz@gmail.com so we get in touch? Thanks!

**Pull request merged**
