### PR TITLE
Add missing boost and bdwgc libs

### PR DESCRIPTION
**Pull request by intrigus**

### CODE REVIEW

**Comment by soywiz** [comment]
Awesome! Thanks :D

**Comment by intrigus** [comment]
Currently Linux/Mac only.

**Comment by soywiz** [comment]
I added partial windows support last night. It compiles libraries using cmake for gc and bootstrap.bat for boost. Also generates CMakeLists.txt along program.cpp allowing to compile the program manually. I have to build and run the program using cmake too on windows. It should be just calling cmake as im doing that manually for testing and it works flawlessly. I also had to fix JNIAPI methods in windows build that uses _stdcall.

**Comment by soywiz** [comment]
Congratulations! Now that it doesn't get an out of memory, I'm trying it and the performance is outstanding. Executable file size is small, and benchmark performance very similar or better than java in linux and windows at least. Better than D and that Haxe-Cpp in all compilation time, size and raw performance.
Also there is still some optimizations that we can do, like devirtualization in generated code / inlining in constructors. So still can get better, specially in areas like object allocation where Java is still better.

```
JTransc 0.5.16 - cpp
Java 1.8.0_51 - 25.51-b03 - 1.8.0_51-b16
freeMemory: 32768, maxMemory: 296544, totalMemory: 296832
Benchmarking:
plain loops...2.0
shift left constant...5.0
shift right constant...9.0
shift unsigned right constant...9.0
shift left constant long...4.0
shift right constant long...7.0
shift unsigned right constant long...7.0
left shift...16.0
right shift...15.0
right unsigned shift...11.0
call static mult...14.0
call instance mult...13.0
call instance div...73.0
instanceof classes...56.0
arraycopy int...12.0
write byte[]...8.0
write short[]...8.0
write char[]...9.0
write int[]...11.0
write float[]...7.0
write double[]...13.0
String Builder 1...34.0
String Builder 2...12.0
long arithmetic...0.0
simd mutable...38.0
simd immutable...407.0
simd mutable matrix mult...97.0
StringBuilder1...35.0
StringBuilder2...24.0
Create Instances1...49.0
Create Instances2...48.0
Create Instances with builder...587.0
Java's CRC32...53.0
jzlib's CRC32...53.0
compress java's Deflate...18.0
compress jzlib...19.0
random...2.0
exception...15.0
```

```
JTransc 0.5.16 - java
Java 1.8.0_65 - 25.65-b01 - 1.8.0_65-b17
freeMemory: 496961904, maxMemory: 7477395456, totalMemory: 504889344
Benchmarking:
plain loops...2.922154
shift left constant...5.980136
shift right constant...6.239595
shift unsigned right constant...6.364569
shift left constant long...5.977592
shift right constant long...6.242347
shift unsigned right constant long...6.248685
left shift...19.129645
right shift...19.679218
right unsigned shift...20.883179
call static mult...16.085265
call instance mult...15.907817
call instance div...73.980278 [0s]
instanceof classes...15.980221
arraycopy int...16.106381
write byte[]...5.200019
write short[]...6.95381
write char[]...6.961836
write int[]...8.051106
write float[]...10.599318
write double[]...17.181133
String Builder 1...21.655967
String Builder 2...7.527503
long arithmetic...1.444208
simd mutable...10.849287
simd immutable...40.200567
simd mutable matrix mult...51.194674
StringBuilder1...20.782857
StringBuilder2...22.112923
Create Instances1...6.21E-4
Create Instances2...7.23E-4
Create Instances with builder...16.340411
Java's CRC32...12.793268
jzlib's CRC32...53.457518TING [1s]
compress java's Deflate...14.308639
compress jzlib...20.652924
random...6.84869
exception...7.063166
```

**Comment by intrigus** [comment]
I know many optimizations which additionally can be applied :)

**Pull request merged**
