### PR TITLE
fix out of memory

### PR DESCRIPTION
**Pull request by SergeyLabutin**

### CODE REVIEW

**Comment by soywiz** [comment]
Ok. Before merging this, I need to know in which target it produces an out of memory. As far as I understand this is a compilation/runtime problem in the target platform this would just mitigate the problem, but won't fix it completely.
It's because a class is too big? Methods sizes would be exactly the same. But again if DynamicNewInvoke or DynamicGetSet grows even more, we would have the same problem.

So please, tell me which target fails and I will try to come up with something more scalable (even trying to split that method in several methods or even creating classes dynamically at compile time)

**Comment by SergeyLabutin** [comment]
Yes. With examples works fine without this fix. But 2 our project (i can not show, because this commerce projects and i have NDA) out of memory from haxe to cpp convertation. Class with reflection very big, about 17m. We try find solution for our projects only. We have >65K classes and for android use multidex. With GWT use xml with minimum defination classes for reflection class have <65K lines, java can not compile big files. But we try find solution for no monkey job with any xml with jtransc. I think any big project will be confused with this problem.

**Comment by soywiz** [comment]
Ok. I'm merging it so you can use the fix already and I will try to generate ton of synthetic classes to  reproduce the problem and try fix it.

**Comment by SergeyLabutin** [comment]
Tnx

**Pull request merged**
